### PR TITLE
chore: use element as key for entries

### PR DESCRIPTION
**Pull request by marstamm**
related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/712

test it out using 
```
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel -l bpmn-io/properties-panel#use-element-as-key
```

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Just to make sure, does this still work with the Linter (showing the errors in the Properties panel, although the inputs are not visible)?

**Review by pinussilvestrus — COMMENTED** [review]
I integration tested this one together with Linting in the Camunda Desktop Modeler, and everything seems to work as expected. 👍 

I'd be up for trying this out but wait for another ✅  as it is a pretty core change.

**Comment by nikku** [comment]
@pinussilvestrus Do you approve this? If so, please :heavy_check_mark: :slightly_smiling_face:

**Review by pinussilvestrus — APPROVED** [review]
Go for it 🤞

**Pull request merged**
