### PR TITLE
fix(hooks): don't break on missing scrollContainer

### PR DESCRIPTION
**Pull request by marstamm**

### CODE REVIEW

**Comment by philippfromme** [comment]
So I assume you have the context and this is a regression caused by https://github.com/bpmn-io/properties-panel/commit/0ffe26bd7b11da61c3e3d7cd2abd651c7baa6b13? I'm asking because I didn't get this error.

**Comment by marstamm** [comment]
Yes, this is a regression caused by #238 . Basically, we assume that the `scrollContainer` DOM query will return something, which is not the case when it is unmounted.

Here, I just added a check to verify that `scrollContainer` exists before we access it

**Review by philippfromme — APPROVED** [review]
✅

**Comment by barmac** [comment]
Unfortunately, the test case is green even when the fix is removed.

**Pull request merged**
