### PR TITLE
fix: move popout close button to header

### LINKED ISSUE #364: Close button of popup editor overlaps text during editing
### Describe the Bug

Currently, the close button is overlapping some of the feel text when editing. This causes 

grafik

### Steps to Reproduce

1. Pop a feel expression out
2. Enter a bunch of text into it
3. See above picture

### Expected Behavior

3. There should not be a conflict between this button and the text display. Move the Close button to the top bar of the FEEL Popup Editor. The area below will be reserved only for editing and previewing FEEL expressions.

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #364

### CODE REVIEW

**Comment by nikku** [comment]
@Skaiir Please share a preview (capture) of the proposed interaction.

**Comment by Skaiir** [comment]
So the preview of what was proposed is the following, available in the issue referenced.

image

The tooltip is not included here as we currently do not make use of these in the editor. Might be interesting to take on later.

**Comment by nikku** [comment]
We use the `sr` tool and want folks to add screenshots / captures to _every_ PR so reviewers can quicker and easier relate to a given change and/or try it out. We'll ask for it again, in the future.

**Review by nikku — APPROVED** [review]

**Comment by nikku** [comment]
@Skaiir You go ahead and release these changes?

**Comment by Skaiir** [comment]
@nikku Will do after lunch time :)

**Comment by nikku** [comment]
Released with [v3.20.1](https://github.com/bpmn-io/properties-panel/releases/tag/v3.20.1)

**Pull request merged**
