### PR TITLE
fix(FEEL): buffer `focus` events without offset

### PR DESCRIPTION
**Pull request by marstamm**
Recording 2022-11-15 at 13 46 24

related to https://github.com/camunda/camunda-modeler/issues/3276

### CODE REVIEW

**Comment by marstamm** [comment]
Actually, I was to quick with this one. It does not scroll into view. Moving to draft again.

Recording 2022-11-15 at 13 57 04

**Comment by marstamm** [comment]
Scrolling is fixed by https://github.com/bpmn-io/feel-editor/pull/30

**Comment by marstamm** [comment]
Ready for review now

**Review by philippfromme — APPROVED** [review]
✅

**Pull request merged**
