### PR TITLE
style: use consistent add/arrow color also for empty sections

### PR DESCRIPTION
**Pull request by MaxTru**
addColor

Related to camunda/camunda-modeler#2664

### CODE REVIEW

**Review by smbea — APPROVED** [review]
LGTM ✅

**Comment by andreasgeier** [comment]
@MaxTru pls provide an artifact to test

**Comment by MaxTru** [comment]
Sure, please start via running the following:
```
 npx @bpmn-io/sr "bpmn-io/bpmn-js-properties-panel" "-l=bpmn-io/properties-panel#same-button-color-for-all"  
```

Let me know, in case I can support

**Review by andreasgeier — APPROVED** [review]
✅ Approved based on a review of the cloud panel. I assume that the platform panel and the templates are considered, too.

**Comment by MaxTru** [comment]
> white_check_mark Approved based on a review of the cloud panel. I assume that the platform panel and the templates are considered, too.

They are :-)

**Pull request merged**
