### PR TITLE
chore(CHANGELOG): update to v0.14.0

### PR DESCRIPTION
**Pull request by pinussilvestrus**

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
If we merge https://github.com/bpmn-io/properties-panel/pull/151 and this didn't get merged beforehand, let's include the sticky headers as well 👍 

/cc @MaxTru @barmac

**Comment by MaxTru** [comment]
> If we merge #151 and this didn't get merged beforehand, let's include the sticky headers as well +1
> 
> /cc @MaxTru @barmac

Sticky headers arrived :-)

**Comment by MaxTru** [comment]
@pinussilvestrus added sticky headers note. LGTM! Feel free to merge

**Comment by pinussilvestrus** [comment]
I will bump the version alongside https://github.com/bpmn-io/bpmn-js-properties-panel/pull/687 👍

**Pull request merged**
