### PR TITLE
fix(FEEL): show syntax errors

### PR DESCRIPTION
**Pull request by marstamm**
try it out using 

```
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel -l bpmn-io/properties-panel#feel-editor-syntax-error
```

image

requires https://github.com/bpmn-io/feel-editor/pull/10

### CODE REVIEW

**Comment by philippfromme** [comment]
I'm reviewing this. 👀

**Comment by philippfromme** [comment]
When there's an error, and I start typing, the error will only disappear after denounced linting has finished. I would expect the error to disappear when I start typing.

brave_C37xTP6SfT

On the other hand, in the Camunda Modeler, linting errors coming from the BPMN linter will behave the same. 🤔

**Comment by marstamm** [comment]
I would keep it consistent with what is shown in the editor. As CodeMirror still shows error markers after we started typing, we should keep the error message in the properties panel as well.

VSCode seems to do the same, but with a much smaller delay. We could think about lowering the delay until linting is executed (default is 750ms), but that would be done on the `@bpmn-io/feel-editor` part

**Comment by marstamm** [comment]
@philippfromme , should we merge and include this one in the next modeler release? The improvements mentioned in my previous comment have to be done as a follow-up in the `feel-editor` repo anyway.

**Review by pinussilvestrus — APPROVED** [review]
This looks good to me! Let's merge, any further improvements can be improved as follow-up (as @marstamm  suggested).

**Pull request merged**
