### PR TITLE
fix: do not grow autoresized text area on first input

### PR DESCRIPTION
**Pull request by barmac**

### CODE REVIEW

**Comment by nikku** [comment]
Thanks for looking into this. I don't understand why the `scrollHeight` check should be necessary. We enforce a minimum height via CSS. Removing it (https://github.com/bpmn-io/properties-panel/pull/216/commits/b1b8a108fe9299171702429952a26fc2e354a31d) the test still passes.

There is a couple of nuances that we need to be aware on non MacOS systems regarding scrollbars. Scroll height will always be < then offsetHeight once resized, hence we must make the actual height magic `2px` bigger than scroll height:

capture QmX6JA_optimized

If we don't do that then a pesky scrollbar appears every time we auto-resize.

Finally, revisiting this I find that our cap of `150px` is an arbitrary one, and dangerous, too. We'd need to properly handle manual user resize in order to turn that into a meaningful thing. I've removed it via https://github.com/bpmn-io/properties-panel/pull/216/commits/29e9612879ca7e480f2dfa001751ab72fc862777.

Please check if `rows=1` was the actual fix for the issue. Consider squashing my PRs then.

**Review by nikku — CHANGES_REQUESTED** [review]
I think this can be simplified, and `+ 2px` must be kept: https://github.com/bpmn-io/properties-panel/pull/216#issuecomment-1421417303.

**Comment by barmac** [comment]
It still grows on MacOS / Chrome. It looks like the +2px causes this:

https://user-images.githubusercontent.com/28307541/217468875-a9b90fd8-f7c3-477d-94a7-e395008fa71f.mov

**Comment by barmac** [comment]
> Please check if rows=1 was the actual fix for the issue. Consider squashing my PRs then.

`rows=2` makes it grow to 2 lines height on my machine.

**Pull request merged**
