### PR TITLE
fix(FEEL): reported error switching

### PR DESCRIPTION
**Pull request by smbea**
Related to https://github.com/camunda/camunda-modeler/issues/3845

### CODE REVIEW

**Comment by nikku** [comment]
Do you remember why we had `local > global` in the past? And can you make a good call for `global > local`? I'm happy to merge this, we just want to ensure we know why this is a good direction.

**Comment by smbea** [comment]
> Do you remember why we had local > global in the past?

I don't really know. I guess it's so the user can get the most context: a syntax error is more specific than just "not valid"

> And can you make a good call for global > local?

I vouch for this because you can still get the syntax error by hovering the highlighted area.

image

**Comment by nikku** [comment]
Thanks. Makes sense to me, along with prior discussions in https://github.com/camunda/camunda-modeler/issues/3845#issuecomment-1721081797 and following.

If there is a global (in the larger context) error provided, we'll always show that _over_ the local error.

**Review by nikku — APPROVED** [review]

**Comment by nikku** [comment]
Thinking about it `global` should rather be called `externally provided` to make that clear. Not required for this fix though.

**Pull request merged**
