### PR TITLE
chore(TextField): use controlled input

### LINKED ISSUE #146: Debounced Input Sometimes Loses Input
__Describe the Bug__

 Due to the debounced input (cf. https://github.com/bpmn-io/properties-panel/blob/main/src/components/entries/TextField.js#L38) sometimes the input is lost. As the component is controlled after the debounce delay the value is passed back to the input as a prop and will override any input that happened inbetween.

__Steps to Reproduce__

1. Focus a `TextField` input
2. Type rather fast
3. Sometimes the input is lost

__Expected Behavior__

No input is ever lost while the input is focused.

__Environment__

- Library version: 0.13.1

### PR DESCRIPTION
**Pull request by marstamm**
closes #146

test it with 
```
npx @bpmn-io/sr bpmn-io/bpmn-js-properties-panel -l bpmn-io/properties-panel#input-focus
```

### CODE REVIEW

**Comment by marstamm** [comment]
As we just changed from uncontrolled to controlled input, I can't think of a test case that would behave differently. Let me know if you have any Idea on how to test for this weird glitch.

**Comment by nikku** [comment]
I can still (rarely) reproduce it on `<textarea>`. I can no more reproduce it on text fields.

**Comment by marstamm** [comment]
I was not aware that it was also am issue in Textareas and did not touch them. I will apply the same fix to Textareas :smile:

**Comment by marstamm** [comment]
I could reproduce it on TextAreas and added the same pattern to it. Could not reproduce it after.

ca4f88661d48d4131552e0357e627f50cc28758c

If we find more places where this pattern is needed, it would make sense to extract it to a custom hook, but for just 2 Components I think it is okay to have the code duplicated.

**Comment by pinussilvestrus** [comment]
> If we find more places where this pattern is needed, it would make sense to extract it to a custom hook, but for just 2 Components I think it is okay to have the code duplicated.

Could this also happen on [Number](https://github.com/bpmn-io/properties-panel/blob/main/src/components/entries/NumberField.js) (used in form-js) and [Simple](https://github.com/bpmn-io/properties-panel/blob/main/src/components/entries/Simple.js) entries (used in Camunda Platform 8 Inputs & Outputs - type = List)?

**Comment by marstamm** [comment]
I think it could happen there as well (just looking at the code).

I would propose to merge this one as a fix to close the reported bug and create a follow-up ticket to migrate all components to controlled inputs.

**Review by nikku — APPROVED** [review]
Looks good. :+1:

**Comment by nikku** [comment]
@marstamm Agreed. Please follow up (or create a follow up issue).

**Comment by marstamm** [comment]
Follow-up: https://github.com/bpmn-io/properties-panel/issues/155

**Pull request merged**
